### ISSUE TITLE
'Method' type

### ISSUE THREAD

**Issue by ItamarKieslerFabric** [osskit/monitor#26]
Hi,

The type of the `method` argument is `CamelCase<Method> extends never ? string : CamelCase<Method>`.
IIUC it's meant to give a useful feedback for string literals (for example 'TS2345: Argument of type '"NAME"' is not assignable to parameter of type '"name"'.').
But if I have a variable of type string and I want to pass it as `method` what is the correct way to cast it to the requested type?

Thanks

**Comment by noamokman** [comment]
Hey, we have a test that covers this specific use-case, 
https://github.com/osskit/monitor/blob/main/tests/main.spec.ts#L35-L42
Is this not what you are trying to do?

**Comment by ItamarKieslerFabric** [comment]
Please update typescript version to latest (4.8.3) and you'll see the problem, the tests won't pass type checking.

**Comment by noamokman** [comment]
true,
I'll drop the type checks and just replace any `-` with `_`

**Comment by noamokman** [comment]
@ItamarKieslerFabric can you take a look at #27?

**Comment by ItamarKieslerFabric** [comment]
LGTM, Thanks
